Jonnitto:
  TextWithPlyr:
    defaultAlignment: right
    container: false
    class:
      row: row
      colText: 'col-12 col-sm-6'
      colMedia: 'col-12 col-sm-6'
      hasFloat: clearfix
      hasRow: false
      alignment:
        left: flex-sm-row-reverse
        right: false
        floatLeft: 'float-sm-left my-sm-2 mr-sm-3 maxwith-sm-50'
        floatRight: 'float-sm-right my-sm-2 ml-sm-3 maxwith-sm-50'

Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Jonnitto.TextWithPlyr:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Jonnitto.TextWithPlyr: true
