Jonnitto:
  TextWithPlyr:
    includeMaxFloatWithCss: true
    defaultAlignment: right
    container: false
    class:
      row: row
      colText: 'col-md-6'
      colMedia: 'col-md-6 align-self-center'
      hasFloat: clearfix
      hasRow: false
      alignment:
        left: flex-md-row-reverse
        right: false
        floatLeft: 'jonnitto-textwithplyr--floatleft'
        floatRight: 'jonnitto-textwithplyr--floatright'

Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Jonnitto.TextWithPlyr:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Jonnitto.TextWithPlyr: true
