Jonnitto:
  TextWithPlyr:
    defaultAlignment: right
    container: false
    class:
      row: row
      colText: 'col-12 col-md-6'
      colMedia: 'col-12 col-md-6'
      hasFloat: clearfix
      hasRow: false
      alignment:
        left: flex-md-row-reverse
        right: false
        floatLeft: 'float-md-left my-md-2 mr-md-3 maxwith-md-50'
        floatRight: 'float-md-right my-md-2 ml-md-3 maxwith-md-50'

Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Jonnitto.TextWithPlyr:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Jonnitto.TextWithPlyr: true
